[package]
name = "jamcc"
version = "0.1.0"
authors = ["James Nguyen <jnnguyen705@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
debug = []

[dependencies]
regex = "1.3.9"
lazy_static = "1.4.0"